### ISSUE TITLE
Custom font size

### ISSUE THREAD

**Issue by xQuai** [IS2511/ChatIS#37]
Hello everyone,

would it be possible to set individual font size per pixel instead of the three given options for font size?
We currently need an option between normal and medium. Unfortunately, this is currently not possible.

**Comment by IS2511** [comment]
I got a random surge of motivation and put together all the stuff needed for a custom font size to work ([9b80357](https://github.com/IS2511/ChatIS-v2/commit/9b803575a742a2d566e1df19049a7ac56027c3ba)). But now I'm too lazy to rework the size option UI to add support for custom size...

I can suggest a workaround for the lack of UI option for now. OBS supports custom CSS.

<details><summary>Screenshot of the OBS Custom CSS input box (spoiler)</summary>

![Screenshot at 2024-12-30 00-05-18](https://github.com/user-attachments/assets/dce078e5-a379-4d24-9be8-94c98497b6a7)

</details>

In there you can add:
```css
:root {
    /* Round numbers are recommended. Value is in pixels, do not add 'px' suffix. */
    /* Options from the menu: small - 20, medium - 34, large - 48. */
    --chat-font-size: 20;
}
```
